version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  java-app:
    image: openjdk:17
    container_name: java-app
    working_dir: /usr/src/app
    volumes:
      - ./target:/usr/src/app
    command: ["java", "-jar", "demo-0.1-test build.jar"]
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: